[breakpoints]
'/home/bradn44/Projects/current/Gridlock/tests/mpi_mm.c' = [ 87, 107, 132, 83 ]

[debugger]
default_ranks = 6
gdb_path = 'gdb'

[theme.assembly]
address = '#555555'
opcode = '#00ff7f'
register = '#ff7f50'

[theme.source]
active_line = '#505000'
background = '#1e1e1e'
text = '#f0f0f0'