[breakpoints]
'tests/mpi_mm.c' = [ 49, 132, 68 ]

[debugger]
default_ranks = 6
gdb_path = 'gdb'

[project]
binaryArguments = ''
customGdbPath = 'gdb'
targetBinary = ''
watchExpressions = [ 'numworkers', 'extra' ]
workingDirectory = ''

[theme.assembly]
address = '#555555'
opcode = '#00ff7f'
register = '#ff7f50'

[theme.source]
active_line = '#505000'
background = '#1e1e1e'
text = '#f0f0f0'