[breakpoints]
'tutorial/deadlock_demo.c' = [ 31, 34, 28, 25 ]
'tutorial/inspection_demo.cpp' = [ 76, 36 ]
'tutorial/memview_demo.cpp' = [ 146, 131, 25 ]
'tutorial/memview_diff_demo.cpp' = [ 162, 30, 181 ]
'tutorial/mpi_mm.c' = [ 99 ]
'tutorial/register_demo.cpp' = [ 24, 103, 117, 37 ]

[workspace]
watchExpressions = []